import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import { CrisisSession } from '../types/crisis';

export const exportSessionToPDF = async (session: CrisisSession) => {
  const date = new Date(session.timestamp).toLocaleString();
  const generatedAt = new Date().toLocaleString();

  const html = `
    <html>
      <head>
        <style>
          body { font-family: 'Helvetica', sans-serif; padding: 40px; color: #333; }
          .header { border-bottom: 2px solid #000; padding-bottom: 10px; margin-bottom: 20px; }
          .title { font-size: 24px; font-weight: bold; }
          .meta { font-size: 12px; color: #666; margin-top: 5px; }
          .section { margin-bottom: 25px; }
          .section-title { font-size: 18px; font-weight: bold; margin-bottom: 10px; border-left: 4px solid #F44336; padding-left: 10px; }
          .content { font-size: 14px; line-height: 1.6; }
          .right-item { margin-bottom: 15px; padding: 10px; background: #f9f9f9; border-radius: 5px; }
          .right-header { font-weight: bold; color: #D32F2F; }
          .footer { margin-top: 50px; font-size: 10px; text-align: center; color: #999; border-top: 1px solid #eee; padding-top: 10px; }
        </style>
      </head>
      <body>
        <div class="header">
          <div class="title">LegalLens Evidence Record</div>
          <div class="meta">Generated: ${generatedAt}</div>
        </div>

        <div class="section">
          <div class="section-title">Session Details</div>
          <div class="content">
            <strong>Date & Time:</strong> ${date}<br/>
            <strong>Location:</strong> ${session.jurisdiction.district}, ${session.jurisdiction.state}<br/>
            <strong>Crisis Type:</strong> ${session.detectedCrisis.replace('_', ' ')}
          </div>
        </div>

        <div class="section">
          <div class="section-title">User Statement Transcript</div>
          <div class="content">
            ${session.voiceTranscript || 'No transcript available.'}
          </div>
        </div>

        <div class="section">
          <div class="section-title">Legal Rights Provided</div>
          <div class="content">
            ${session.response.rights.map(right => `
              <div class="right-item">
                <div class="right-header">${right.actName} (${right.actYear}) - Section ${right.sectionNumber}</div>
                <div>${right.description}</div>
              </div>
            `).join('')}
          </div>
        </div>

        <div class="section">
          <div class="section-title">Timeline Trail</div>
          <div class="content">
            - [${date}] Crisis detected and session started<br/>
            - [${date}] Legal rights displayed to user<br/>
            ${session.audioRecordingUri ? `- [${date}] Silent audio recording initiated<br/>` : ''}
          </div>
        </div>

        <div class="footer">
          This document was generated by LegalLens for legal reference purposes.
        </div>
      </body>
    </html>
  `;

  try {
    const { uri } = await Print.printToFileAsync({ html });
    await Sharing.shareAsync(uri, { UTI: '.pdf', mimeType: 'application/pdf' });
  } catch (error) {
    console.error('Failed to export PDF', error);
  }
};
